### ISSUE TITLE
No error generated for tokenization failure

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#133]
related to #101 
until 1/28 I was getting a 500 error when uploading a file type as jpg. (I was doing it for testing as I had to reproduce the 500 error). since this morning, I am not longer getting any errors but the tokenization process is finished with no alignment groups generated. in FF I got the yellow message and froze the tab. I would rather see the 500 error message again.
see attachment

![Screen Shot 2021-01-29 at 9 59 39 AM](https://user-images.githubusercontent.com/41396793/106254413-f68b6600-6218-11eb-98eb-43c576adc504.png)

**Comment by monzug** [comment]
this is the browser error message in FF 
![Screen Shot 2021-01-29 at 11 31 44 AM](https://user-images.githubusercontent.com/41396793/106264218-ae267500-6225-11eb-8e08-55992eeae347.png)

**Comment by monzug** [comment]
and the console
![Screen Shot 2021-01-29 at 11 33 25 AM](https://user-images.githubusercontent.com/41396793/106264357-d7df9c00-6225-11eb-8568-833515896653.png)

**Comment by irina060981** [comment]
From my tests there are no errors besides problems with image size.
I do the same test - uploaded 2 small png files.
Their contents were uploaded to the textarea (the same as on your screenshot)
And then clicked Align - and this content was passed to the tokenizer.
The language model for parsing was defined from language property (in my case - english).
And tokenizer divided it to tokens and returned the result - that's why you recieved successfull notifications.

But the rendering of the page froze because of too big amount of tokens - for now we don't have any limits for a text length.

So there is no bug in the workflow - only limits of the performance.

I believe that we could do the following here (as a future requirements):
- add rendering for tokens edits by request but noy by default - it would decrease the amount of first rendered tokens
- add rendering by parts (segments or sentences)
- add limits for amount of tokens

**Comment by balmas** [comment]
I agree we need to add limits for the text length at this point.

**Comment by monzug** [comment]
also file type: e.g. jpg not a valid file type?

**Comment by irina060981** [comment]
>also file type: e.g. jpg not a valid file type?
- added a check for available file extensions

**Comment by irina060981** [comment]
>I agree we need to add limits for the text length at this point.

Suggest to continue discussion in https://github.com/alpheios-project/alignment-editor-new/issues/140

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
jpg gives an error.

**Comment by irina060981** [comment]
Oh - you are right - I would extend the error message.
Available extensions:
from main menu - csv/tsv and json
from text single instance menu - txt and xml

I could add other variants to the text single menu - but they would be uploaded as text - as is

**Comment by irina060981** [comment]
Would be this way

![image](https://user-images.githubusercontent.com/12377640/106687558-12777900-6618-11eb-9ade-df4dceee03c9.png)

![image](https://user-images.githubusercontent.com/12377640/106687597-258a4900-6618-11eb-8aee-de25cc3b725c.png)

**Comment by monzug** [comment]
valid file types: csv, tsv and json for top upload, txt, xml, csv and tsv for origin or target upload
