### ISSUE TITLE
Tokenization works but alignment is empty for XML file from Ugorit

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#176]
Upload a xml file saved from Ugorit in Origin and target text. Tokenization process ended with no error, however the alignment groups is empty. As we are talking to use xml files from other applications too, I am afraid that this could be a frequent issue.
I am not sure what would be the best way to go. Maybe if alignment group is empty throwing an error but I doubt it would be easy to determine when an alignment is empty. or checking for missing tags and throwing an error.

![Screen Shot 2021-02-09 at 3 30 51 PM](https://user-images.githubusercontent.com/41396793/107378100-ee220d80-6aeb-11eb-8603-377ba10c9de8.png)

see below the file from Ugorit
[ugarit-aligner-1612854747064.xml.zip](https://github.com/alpheios-project/alignment-editor-new/files/5951988/ugarit-aligner-1612854747064.xml.zip)

**Comment by monzug** [comment]
see https://github.com/alpheios-project/tokenizer/issues/29

**Comment by irina060981** [comment]
I looked to the attached file - and it is not a tei xml, I believe it is a specific Urgorit file format for created alignment.
For now we don't have a parser function for these types of files.
It is out of the current requirements. Let's ask Monica and Harry.

**Comment by monzug** [comment]
Yes. Thanks!

**Comment by balmas** [comment]
This is an alpheios v1 alignment xml file.  (It adheres to the schema used by version 1 of the alpheios alignment editor). We definitely DO want to support this file type in input.

**Comment by balmas** [comment]
as to priority, I guess I will leave that up to @abrasax to say

**Comment by abrasax** [comment]
I'll have to discuss it with monica                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Bridget AlmasSent: Saturday, February 13, 2021 10:22 AMTo: alpheios-project/alignment-editor-newReply To: alpheios-project/alignment-editor-newCc: Harry Diakoff; MentionSubject: Re: [alpheios-project/alignment-editor-new] Tokenization works but alignment is empty for XML file from Ugorit (#176)
as to priority, I guess I will leave that up to @abrasax to say

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/alpheios-project/alignment-editor-new/issues/176#issuecomment-778633378",
"url": "https://github.com/alpheios-project/alignment-editor-new/issues/176#issuecomment-778633378",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by irina060981** [comment]
For now an application could upload xml from Ugarit (it is Alpheios v1 format).
It is available from Resume previous alignment - now you could use our JSON format or XML from Ugarit.

**Comment by monzug** [comment]
xml import works with both 2 and 3 languages. also the groups of words are imported correctly in the Alpheios alignment editor. well done.
