### ISSUE TITLE
Unclear message when uploading target text before origin text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#196]
For some reason, I thought we had a different message when uploading target text before the origin text. Anyhow the current message is "Choose another token please - from the same segment, target text." which does not provide the information needed. Irina, can you check if we used to generate a different message? if not, can we add a message with meaningful information for this situation?

![Screen Shot 2021-02-15 at 4 44 56 PM](https://user-images.githubusercontent.com/41396793/107967358-4c983180-6fad-11eb-929c-4bfdd0f85603.png)

**Comment by irina060981** [comment]
This error is a bug (it is from another part of the application) - I removed it.

We have a requirement that first a user should define origin and only then targets texts.
So I added this limit.

on first load - 
origin part is enabled; target is disabled

![image](https://user-images.githubusercontent.com/12377640/108051053-24383200-7096-11eb-9d3c-280e3d5ef091.png)

after a user defines any text in the origin part - target becomes enabled

![image](https://user-images.githubusercontent.com/12377640/108051154-4631b480-7096-11eb-95b6-6a90f5377036.png)

**Comment by monzug** [comment]
yes, it's working as described. However I liked as it was before. in several occasions, I had to copy target text first and then add the origin text (cut and paste from other translations). I personally find annoying to limit this ability. we shall ask Harry what his take is on this one.

**Comment by monzug** [comment]
Actually, if I upload text in target language before entering any text in Origin first, I get the following message
First you should define origin source text.
so I think it's ok the way it is.

**Comment by abrasax** [comment]
My reflexive, not always carefully considered, answer to questions of this
sort is to always prefer not to limit user behavior, not to try to force
them into a preferred sequence unless we really need to and can specify it
clearly beforehand.  I was just trying to tokenize some original text
without anything in the target text box, and found that it wouldn't work
until I had added some dummy text in the target box. There may be a
compelling reason for that, but if so we should probably send an error
message rather than just failing mutely.

**Comment by monzug** [comment]
I share Harry's vision. Irina, what do you think?

**Comment by irina060981** [comment]
We have some base limits that were placed to the structure in requirements and now they could not be changed easily.

For example,
We could not tokenize only origin or only target
We could not get result if we have different amount of segments in texts
We could not create an alignment group with origin from one segment and from target from another segment

And we have not so strict limits in requirements.
For example,
place first origin text and then target (that's why it was available before)

I could remove this unstrict limit because it won't influence on the main tokenize workflow.
Would remove it according to your notes :)

**Comment by monzug** [comment]
absolutely  agree with your comments above and I do not think we need to
change any of this, just a message when I add target first (as it was
before) and still let the user edit this side first and a message when
tokenization occurs with only origin text as Harry described (even if I was
not able to reproduce this scenario in which we only have the Origin text
and tokenization occurs)

**Comment by irina060981** [comment]
ok - let's change only a message

**Comment by irina060981** [comment]
Changed to
![image](https://user-images.githubusercontent.com/12377640/108189410-6deb5000-715c-11eb-8368-5865dcaf0caa.png)

Disabling target textarea - turned off

**Comment by monzug** [comment]
fixed. Now I can edit the target text and getting the following message: First you should define origin source text. THANKS!
