### ISSUE TITLE
Download as json should be allowed only after alignment

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#229]
tested in Alpheios Translation Alignment editor 1.0.2 (build i226-sentence-view-bug.20210223418) 

Global download has two options: Full to json and Short to tsv.
If I only have Origin and Target texts without alignment groups, I can still save as json. I do not see any reason why should I be allowed to do this. Was this a specific requirement? Thanks
also, in terms of priority, this is SUPER SUPER low.

![Screen Shot 2021-02-23 at 3 38 49 PM](https://user-images.githubusercontent.com/41396793/108859887-f9962e00-75ed-11eb-942a-3625543cb2a4.png)

**Comment by irina060981** [comment]
>Global download has two options: Full to json and Short to tsv.
If I only have Origin and Target texts without alignment groups, I can still save as json. I do not see any reason why should I be allowed to do this. Was this a specific requirement? Thanks
also, in terms of priority, this is SUPER SUPER low.

We talked with Harry about it before o the meeting (Monica, you could remember it) and decided, that it is worth to remove short from tsv as an upload/download type from the global menu.
Because it is enough to have only json upload/download from main menu for all cases.

Dwnload/upload from tsv was a created as the first simple approach on the early stages of the development - it was created as a fast temporary solution.
May be it is worth to turn off it before merging to production. @monzug , what do you think?

**Comment by irina060981** [comment]
Turned off download as csv from main menu, because it was used on the first stages of development.
Full to json - the only one that shoudl be used for global download of data (besides HTML output).

**Comment by monzug** [comment]
tested in Alpheios Translation Alignment editor 1.0.2 (build development.20210226340). Full to json is the only option for download before alignment, after alignment we also have the html output.
