### ISSUE TITLE
Can we reset to default values after reloading the alignment editor?

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#280]
After I reload the page, language, Tei/Text and Max Char per text are sticky. they keep the value of previous alignment. I do agree that in Clear text, this scenario is ok as I am expecting to only clear the texts in Origin and Target language.  On reload, I would prefer to have the default values back. I believe we do not have set default values but we can use the one available on a fresh install of the alignment editor.

**Comment by irina060981** [comment]
Monica, we have the defined workflow for options (from requirements) - they are saved in local storage - the same way as we save them in Alpheios Reading Tools.

We save all global:
![image](https://user-images.githubusercontent.com/12377640/110704909-5c6c0400-8241-11eb-8a52-be0cd4840c52.png)

And save all local:
![image](https://user-images.githubusercontent.com/12377640/110704961-6beb4d00-8241-11eb-9fcf-6683032183a6.png)

We have Reset Options button to reset to default (similiar to Alpheios Reading Tools)

I have a request from you to reset to default sourceType to Text (couldn't find it among opened issues - but I remember it).
I would do that because I agree that it could be useful for using with different type of texts.

But if you suggest to change the options workflow for global options (max per text) - than we should discuss it with @balmas and @abrasax

**Comment by monzug** [comment]
I think you are right that Reset all should be sufficient as we decided in
the past with Bridget.

**Comment by irina060981** [comment]
Monica, Reset all button - resets all options field including language and sourceType.
Do you think it is enough for reseting language and sourceType also?
Or I should add reseting on page reload and clear text for language and sourceType as we talked before?

If you suggest to reset everytime than let's stay this issue opened - I would work on it later.

**Comment by monzug** [comment]
I think the combination of Clear text and Reset all should be sufficient. Basically Reload and Clear text are doing the same thing. I am going to postpone this one for future development.

**Comment by monzug** [comment]
I think the combination of Clear text and Reset all should be sufficient. Basically Reload and Clear text are doing the same thing. I am going to postpone this one for future development.

**Comment by irina060981** [comment]
This is done with https://github.com/alpheios-project/alignment-editor-new/issues/327

**Comment by monzug** [comment]
Irina, could you explain what this fix should do on reload? I did reload the alignment editor on Chrome and in Options, I still had few options checked so I needed to use reset all. Thanks

![Screen Shot 2021-04-30 at 2 42 20 PM](https://user-images.githubusercontent.com/41396793/116700349-f8ef8e80-a9c6-11eb-85cd-4f984e63fdcf.png)

**Comment by irina060981** [comment]
>Irina, could you explain what this fix should do on reload? I did reload the alignment editor on Chrome and in Options, I still had few options checked so I needed to use reset all. Thanks

The application doesn't reset global options that is visible on Options screen.
It resets local text options (following is the issue text):

>After I reload the page, language, Tei/Text and Max Char per text are sticky. they keep the value of previous alignment. I do agree that in Clear text, this scenario is ok as I am expecting to only clear the texts in Origin and Target language. On reload, I would prefer to have the default values back. 

I didn't reset max characters - because it is global option - one for all texts at once.

**Comment by monzug** [comment]
with this issue, language and TEI/text are reset to default English and text by Start a new alignment or reset previous.
tested in Alpheios Translation Alignment editor 1.3.3 (build development.20210503268)
