### ISSUE TITLE
Max characters per text tooltip

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#281]
I noticed few minor inconsistencies with this field.
the tooltip is different in FF vs Chrome. I haven't been able to generate it in Safari. in Chrome, it says "Value must be less than or equal to 50000." and it's not highlighted in red.
in FF, tooltip is "Please select a value that is no more than 50000."  and it's highlighted in red.  Are these tooltips browser specific?

I am glad that I am still able to edit the field and go over the max char limit. Hope there is not plan to change this.

**Comment by irina060981** [comment]
>the tooltip is different in FF vs Chrome. I haven't been able to generate it in Safari. in Chrome, it says "Value must be less than or equal to 50000." and it's not highlighted in red.
in FF, tooltip is "Please select a value that is no more than 50000." and it's highlighted in red. Are these tooltips browser specific?

Yes this tooltip is defined by browser by the following:
the field for max characters is defined as number type with maxValue.
And this tooltip is generated by the browser with maxValue.

@monzug , I think I could close it :)

**Comment by monzug** [comment]
Just one thing, I was not able to generate it in Safari. any idea?

**Comment by irina060981** [comment]
These tooltips are completly dependent on browser (type, version).
We have no influence on it.

As for Safari - there are could be different reasons:
 - this type of tooltips are not defined for the Safari (I was not able to see it in 14.0.3)
 - we need to place input tag inside form tag (I didn't do that  because it is not a classic form and this tag is not needed for practical purposes)
 - there are some additional requirements for Safari browser

I searched about this issue (built-in tooltips for Safari) but didn't find information about it. 
Didn't spend much time on it - because anyway it is only a bonus from browsers :)

@monzug, do you think I need to spend time on this issue or we could close it?

**Comment by monzug** [comment]
let's postpone this for the moment. I do not think we have many Safari users. we should ask @balmas to tell us more about which browsers are popular.
