### ISSUE TITLE
Failed download with misspelled language in Other language 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#296]
related to #153 
I did enter a non existing language or Ukainian (misspelled for Ukrainian in the language drop-down, see #294 ). When I went to download the alignment as html output, it did not do anything. I was expecting to see an error in the alignment editor, though there were two errors in the console. Expected result: generate an error in the alignment editor. see attachment:

![Screen Shot 2021-03-18 at 3 06 12 PM](https://user-images.githubusercontent.com/41396793/111639903-f7de1580-87fb-11eb-83b3-0e9f83b76445.png)

I was able to download both the json file and the tsv file with the invalid language and no error in the console. I guess they use different part of the code to check if language is valid.

**Comment by irina060981** [comment]
The application doesn't check the field - `Or Other Language:`, because it works the following way: 

- if you type lang code (ISO 3 characters) thst is known and listed in the dropdown, then language select would be updated with it :
![image](https://user-images.githubusercontent.com/12377640/111720011-d25b1580-88a8-11eb-9c10-761a578b8d53.png)

Click enter/or unfocus the input
![image](https://user-images.githubusercontent.com/12377640/111720066-ebfc5d00-88a8-11eb-90da-63b8183ac38b.png)

- if you type anyting that does not registered as a lang code in our list, than it would be considered as a lang code and as a lang name

So you could download json and HTML with such a language that is defined as Other language.
The error is the bug with defining language Name for printing HTML for such languages - I fixed it

**Comment by monzug** [comment]
ok, so now I am able to download a html output with any language name. this is consistent with tsv and json downloads.
Alpheios Translation Alignment editor 1.3.1 (build development.20210319 83)
