### ISSUE TITLE
New workflow after First you should define original source text. error

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#335]
tested in build Alpheios Translation Alignment editor 1.3.2 (build i327-new-text-editor-screen.20210419378) 

if I upload a file in the Translation text before uploading the Original, the following error message is generated: First you should define original source text. and this work as previous builds. Two issues here:

1) the Translation area where I uploaded the file is empty, though tsv file is not.
2) The new workflow does not allow the user to upload a new file after uploading or editing the Original text. Type in text in the Translation area is possible but not Uploading a new file.

![Screen Shot 2021-04-19 at 3 18 16 PM](https://user-images.githubusercontent.com/41396793/115246639-5d3c6380-a126-11eb-8690-b19cb48a193d.png)

**Comment by irina060981** [comment]
@monzug , I don't know how to handle with it correctly

Why we could not define target before origin, because on origin creation step we create the main object Alignment (inside it all texts are stored). So the workflow is the following:
- create original -> first create Alignment and inside it original
- create translation -> check if Alignment exists, if yes - creates translation inside it, if not - shows a error and doesn't create translation

The difference between paste in and upload the following:
- a user types in/pastes in something it is not saved until text box is unfocused; when a user clicks outside - app tries to save translation - fails because Alignment is not created. A user still sees the text in text box (because app doesn't clear it), but it is not saved.
- a user uploads text - it try to create translation - fails and text doesn't upload to the text box

So there are two ways to go:
- to allow creation from translation (we talked about it before and rejected)
- to clear text box after fail (but may be it could upset a user to loose all typed in text)
- to paste text from file (but it would be inconsistent behavior)

@monzug what do you think?

**Comment by monzug** [comment]
well, an option would be to have the Translation side acts like after the Delete button, so delete the entire entry. so user is forced to start from scratch and from the Original. do you think it would be possible?

**Comment by irina060981** [comment]
>well, an option would be to have the Translation side acts like after the Delete button, so delete the entire entry. so user is forced to start from scratch and from the Original. do you think it would be possible?

@monzug,  do you mean - to print an error notification and return text part to the initial state:

![image](https://user-images.githubusercontent.com/12377640/116024069-c543fa00-a690-11eb-8def-7f5f4e6d1549.png)

**Comment by monzug** [comment]
there are 2 issues here:
1) if I upload a tsv file in the translation first, the text area is left empty and the error message is displayed. If I type in some text in the translation first, the text is still available after the error message is generated. and this is inconsistent. I understand from your explanation the logic behind, and we should handle this better also because of below issue:
2) after the error is generated, even if I have text in both Original and Translation, the Align button is not selectable (grey out). However, if I click on Clear text and type in the same text again (starting from Translation text), the Align button is available this time.

so there are some glitches here. as I suggested above, we should prevent from uploading or typing in text in Translation before the original text, specially if then align button does not work. This was working in the old workflow.

**Comment by irina060981** [comment]
As in #349 we returned empty text box from the start - now it works the same as it was in previous design

**Comment by monzug** [comment]
Uhm, both issues reported above are still reproducible in Alpheios Translation Alignment editor 1.3.3 (build development.20210430.74)

if I enter text in the translation first, then after message is generated I enter text in the Original text. The Align button (or Prepare texts for alignment) is not available in slide menu and in 

![Screen Shot 2021-04-30 at 4 49 20 PM](https://user-images.githubusercontent.com/41396793/116712410-1e36c980-a9d4-11eb-8776-c7dd7d600de6.png)

**Comment by irina060981** [comment]
@monzug, I checked the way it works previously in old version published on https://alignment.alpheios.net/
And now it works the same - it was not delete text before.

Do you prefer to clear text box after getting error - "First you should define original source text"?

**Comment by monzug** [comment]
I would let the user go ahead with the alignment (like it was in our old version before changing the workflow). otherwise I would go as per google translate, not allowed to edit if original text hasn't been entered first.

**Comment by irina060981** [comment]
Ok - I would prevent from changing translation first

**Comment by monzug** [comment]
not longer reproducible
