### ISSUE TITLE
IndexDB: aligned text has missing parts in Original and Translation

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#424]
this is a scenario very similar to the one reported by email of the missing Translation.
upload text from DTSAPI (can be Latin and Greek). I used same text in Original and Translation for detecting lines easily. The aligned text has 2 pages as I see one next and prev. I did some cross alignment: align a word from the next page of Original with a word from prev page of translation. I did it 2 or 3 times, then mouse over one word and see the text will move to the correspondent word on the other side. Then you'll see that there are any alignments left. There will not be any next or prev to scroll. Basically the first part of the Original and Translation text is gone. 
I saved the json files.

this is the alignment output with missing part
![Screen Shot 2021-06-14 at 3 53 53 PM](https://user-images.githubusercontent.com/41396793/121903622-c86e7480-cd28-11eb-8a37-22d6ae1847c4.png)

this is the screenshot of the uploaded texts
![Screen Shot 2021-06-14 at 3 53 25 PM](https://user-images.githubusercontent.com/41396793/121903629-c99fa180-cd28-11eb-9b34-d6aa301d38d5.png)

**Comment by monzug** [comment]
this is the json file before any alignment

[14-06_15-20-full-alignment-lat-lat.json.zip](https://github.com/alpheios-project/alignment-editor-new/files/6654923/14-06_15-20-full-alignment-lat-lat.json.zip)

same file after alignment and disappearing of text

[14-06_15-25-full-alignment-lat-lat.json.zip](https://github.com/alpheios-project/alignment-editor-new/files/6654927/14-06_15-25-full-alignment-lat-lat.json.zip)

**Comment by monzug** [comment]
still reproducible in Alpheios Translation Alignment editor 1.4.1 (build development.20210616302)  after clearing all alignments.

**Comment by irina060981** [comment]
@monzug, could you record a video from the screen with opened console, this way I would probably see some information - for now I don't have idea - what is the problem here, as I could not reproduce it.

**Comment by monzug** [comment]
https://user-images.githubusercontent.com/41396793/122539595-c42aab80-cff5-11eb-83a3-0a5d7ea29491.mp4

**Comment by monzug** [comment]
tested in previous version (before indexDB) and it's not reproducible as we did not have next and prev.
as soon as I align one word from original with two words from translation, I get the next page empty with only prev and next.

**Comment by irina060981** [comment]
@monzug , I need to see the whole scenario (from the reload page) - I should see if it is a new text, or from json, or from IndexedDB.
And also I need to see console - otherwise I couldn't guess what is the error here - that there is no tokens for the part.
For MAC Safari it would be opened by Option + Command + C

I still could not reproduce it by clicking as you on my texts.

**Comment by monzug** [comment]
See below the last recording without console

https://user-images.githubusercontent.com/41396793/122776065-0a5c6500-d2ab-11eb-92fb-ca96f892ae88.mov

see screenshot of the console. could not run together, console went in the background
![Screen Shot 2021-06-21 at 4 10 11 PM](https://user-images.githubusercontent.com/41396793/122776298-442d6b80-d2ab-11eb-98bf-9e91f0263949.png)

**Comment by irina060981** [comment]
@monzug , As I could see delay - there could be some errors in the console.
You made a screenshot only of the part of the console with some delete logs (I believe you did it before - as you don't delete anything in the video)

I need to see console errors (the whole console log) for the moment when you have text disappered

I believe that your console is unpinned from the browser that's why you could not show it together with browser window.
You could pin it back - here are steps:

**Comment by irina060981** [comment]
Console is unpined after clicking Options + Command + C

<img width="1231" alt="Screenshot 2021-06-22 at 09 47 51" src="https://user-images.githubusercontent.com/12377640/122841385-1a258900-d33f-11eb-9b63-f031743b0971.png">

Click the upper left icon 
![screenshot2](https://user-images.githubusercontent.com/12377640/122841880-90c28680-d33f-11eb-9172-d688317f7522.png)

And it would be become this
<img width="1398" alt="Screenshot 2021-06-22 at 09 48 12" src="https://user-images.githubusercontent.com/12377640/122841897-9cae4880-d33f-11eb-8b10-6719f50931b2.png">

**Comment by irina060981** [comment]
And if you would record video this way - console would be synced with the actions in the browser - and I would be able - what error is printed for the moment when text is disappered

**Comment by irina060981** [comment]
oh, great - it's a reproducable scenario - I could reproduce it both on PC(Chrome) and Mac(Safari)
Would investigate - it is godd that it is browser/platform unspecific - then it should be my bug and not a bug of the IndexedDB support. It is good news :)

**Comment by irina060981** [comment]
@monzug , I believe I found the problem.
There was a bug:
when you activate alignment group, or merge with another alignment group - it was resaved all the alignment (an that's way delete all tokens from invisible parts) instead of simply deleting only activated alignment group.

Now it is fixed.
I tested both case - tokens are note deleted.
Hope, the bug is gone.

**Comment by monzug** [comment]
This is not longer reproducible in Alpheios Translation Alignment editor 1.4.1 (build development.20210622.39). Thanks
