### ISSUE TITLE
Annotations type can't be added or remove once in align text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#467]
related to enhancement #462 
annotation type can be defined in Options when in Enter Text. When I go to Align Text, I do not have the possibility to change the type of annotations by adding one (e.g. add comment when I have only lemmaID) or remove one from the list. the field is not longer editable. this can be annoying specially when working with indexedDB file.
why do we have this limitation?
also, why don't we move this field in Options in Align Text rather than in Edit Text?

**Comment by monzug** [comment]
I would simplify the annotations by removing this setting from Options in Enter Text and just have the 3 types available in the drop-down when entering an annotation.

**Comment by irina060981** [comment]
It was a requirement specifically defined by Bridget:

from @balmas email :
about defining settings 

I think the simplest way to implement the annotation fields right now
would be to just extend the default app settings to include a setting
that contains a multi-select list of possible token-level annotation
fields to make available. It could just be a simple list of field names,
e.g. maybe just these to start:

* lemma

* morphology

* comments

Each field would just name a separate string-based annotation field, and
we wouldn't for now enforce any validation that what they have entered
is actually what the name of the field is.  So, if they put something in
the lemma field that isn't a lemma, that's their problem.

The user could select as many (or none) to include in the annotation
interface.  It would apply to all alignments they create, until they
change it.  If their selections don't match what is actually in data,
then the data would just be carried forward the way it is, but not be
editable by the user.

And maybe we could prevent them from making changes to this option while
they have an active alignment loaded, so that they can't change
mid-stream.  Then, when you are loading an existing alignment, if you
find annotation fields in it that don't match the list they have
selected, you could warn the user that they have fields that don't match
their selections and that they will be retained as-is but not be
available for editing.

_Originally posted by @irina060981 in https://github.com/alpheios-project/alignment-editor-new/issues/462#issuecomment-893386622_

**Comment by irina060981** [comment]
I think this issue is not for me - if you want to change the requirement you should discuss it with @abrasax

**Comment by monzug** [comment]
Thanks Irina. I read the requirements in the enhancement #462. I just want to know if there is a specific reason behind these requirements.

**Comment by irina060981** [comment]
Decided to have all 3 annotation types as default on the meeting.
done in the PR
