### ISSUE TITLE
can undo a grouped token in edit text

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#542]
see related issue #457 
an edited token can be grouped in align text. the problem is that when I go to edit text, the token is shown as part of an alignment group so not editable but if I click on undo, the token will go back to the original state of pre-editing and the alignment group is gone. however in align text, the second token of the alignment group is still in black and his state of part of a group cannot be changed (not by undo or by mouse over).
I would suggest to not clear the edit history of a grouped token in Edit Text but to prevent any editing including undo for a token in an alignment group in Edit Text.

**Comment by irina060981** [comment]
> I would suggest to not clear the edit history of a grouped token in Edit Text but to prevent any editing including undo for a token in an alignment group in Edit Text.

It is much more difficult to implement - because 
- history is a line of done actions
- token history and group history - are separated from each other

For example a token was first edited, then grouped.
A user clicks undo in edit text, then what should do the application? 
it should skip the step and do nothing? the same for redo?
I believe that it is really confusing for the user and also it would be difficult to understand from our undo/redo experience in other applications

That's why the realized workflow is not the best - but it is clear for the user and not confusing.

That's why I don't agree with your suggestion.

If it is important to remove this not nice behaviour I suggest to choose from my two variants:

- transform 2 parallel histories to 1 history - then unso/redo won't be in conflict for two screens (it would need more time to implement)
or
- clear edit history after some alignment group action was done (would be implemented quickly)
-

**Comment by monzug** [comment]
I am ok with any solution as soon as I do not have a token in align text that is still part of group that not longer exists.

**Comment by irina060981** [comment]
Then let's do the simplest - clear Edit Tokens history on changing alignment group

**Comment by irina060981** [comment]
I realized the following workflow:
- a user adds a token to the group
- an application checks if this token was edited (has such a step in history)
- if it was edited - token edit history is cleared otherwise tokens edit history won't be erased

I think that this workflow allows to clear history not often

**Comment by monzug** [comment]
will test after Pietro's release

**Comment by monzug** [comment]
it works fine for the scenario described in this issue. Undo is disable in Edit text and the alignment group is preserved.
