### ISSUE TITLE
message should provide more information when lines are different

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#56]
In the situation in which the origin text and target text have different numbers of lines, the alignment is not possible. The following message is generated: Document source texts would be divided to different amount of segments. so I am expecting that by clicking on Align, the text will be still split in segments. Right now, when I click on Align nothing happens.

if it has not been implemented yet, will use this item as test case.

![Screen Shot 2020-10-29 at 3 40 42 PM](https://user-images.githubusercontent.com/41396793/97598206-fd7ebe80-1a06-11eb-9c1a-3a85db95652e.png)

**Comment by balmas** [comment]
We should make the message clearer but this is expected behavior.  User should fix the segmentation and then reupload.

**Comment by irina060981** [comment]
The workflow is the following here:
We pass to the tokenization service divide by "singleline" by default (we have some problems with doublines feature now).
The service divides each text (origin and each target) to segments.
We have the obligatory rule - the amount of segments should be equal between all texts.

That's why if division to segments returns different amount of segments, we need to cancell the alignment.

May be it is better to use this message then:
```
The tokenization process was cancelled because source texts don't have the same amount of segments.
```

@monzug , @balmas - what do you think?

**Comment by monzug** [comment]
Yes. "source texts" equal to origin and target texts. I prefer if we use origin and target texts again.

**Comment by irina060981** [comment]
This is fixed with https://github.com/alpheios-project/alignment-editor-new/pull/85
