### ISSUE TITLE
File saved in indexedDB would not load

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#588]
Again, I had an issue with the file eng-ita. after saving on indexedDB, it would not load from FF splash screen. No error in the log. Is there anything that I can do for troubleshooting?
Note that the file was created today and that the alignment editor is latest version. The file in question is eng-ita, time 15.23. the second file with the same file name eng-ita was created later.
![Screen Shot 2021-10-29 at 3 58 46 PM](https://user-images.githubusercontent.com/41396793/139448497-e9cd5d8a-4a76-44d1-9b2e-7780a0cef0cb.png)

**Comment by irina060981** [comment]
oh, without any errors in the log - it is strange.
Will think what we can do for examining it

**Comment by monzug** [comment]
@irina060981 I tried to reproduce the scenario in which indexedDB does not load the file and I was able to do it just now.
I reload the alignment editor then I started a new alignment with 3 languages. Next I saved few annotations in each language and I switched back and forward from edit to annotations mode, alos I used the undo/redo few times. I ended up with the problem reported above: file in indexedDB does not load from splash screen. This time I have an error in the log (FF/MAC): I think when there are errors in the file, file cannot be loaded.
![Screen Shot 2021-11-02 at 3 16 47 PM](https://user-images.githubusercontent.com/41396793/139865393-c03eb589-e8ad-4789-889a-2ae87e07da7d.png)

**Comment by irina060981** [comment]
Monica, I am sorry - but these errors are not from our application - it is some errors from chrome - may be extensions, I don't know - there are no details on the screen.

@monzug, I think that it is worth to describe IndexedDB technology in more details.
There are no files stored in IndexedDB - so there could not be a situation that the whole alignment information was lost.
IndexedDB - is a storage of datasets, each of them has its own tables.

Here it is in my Chrome browser (it works almost the same in Chrome, Firefox and Safari) - there is an Application tab in the same place where you see console:

![image](https://user-images.githubusercontent.com/12377640/139968858-5077cee0-fc85-49fb-b13e-035ff4f452c9.png)

You could see Storage => IndexedDB 
This is the place where all application that are used in browser store IndexedDB datasets.
The first on my screenshot is for Alignment Editor - 

![image](https://user-images.githubusercontent.com/12377640/139969011-3205d22b-8f73-4f0c-8fba-7cc8326f962e.png)

You could see here:
 - Security origin - each dataset is attached to url, so production environment has its own dataset
 - Version - each time I update dataset structure I need to update version for compability
 - Object stores - this are amount of tables where all our information is stored
 
Let's open it:

![image](https://user-images.githubusercontent.com/12377640/139969178-85bd002e-e74a-4dd3-91d1-f9b7aefb159d.png)

Each table stores one type of information for all alignments
For example - 
- **AlEditorAlGroups** - stores data for all groups from all saved alignments

![image](https://user-images.githubusercontent.com/12377640/139970037-e44dfbb8-0867-4a52-bfe4-ac47dae81864.png)

 - **AlEditorCommon** - stores all basic information of saved alignment:
 
![image](https://user-images.githubusercontent.com/12377640/139969316-c0aceeff-b7ec-45cb-a2e3-fffc7194ec3d.png)

And when I click Resume previous alignment - it simply opens this table and print data from here:

![image](https://user-images.githubusercontent.com/12377640/139969381-85063da3-c404-41ab-930e-907be22f6cd8.png)

When a user clicks on the link - application collects data from all 9 tables for the alignment

And if a user doesn't see ready alignment (as in your case) - this collecting is failed somewhere. Why it does it without printing an error - it is strange. 
Later I will add additional checks for this case - so if this bug is reproduced we could see some report in the console.
Otherwise I could not find where is the problem - because area is very big.

**Comment by irina060981** [comment]
@monzug , I have added some checks and additional error printing
Check, please, on previous broken alignments

**Comment by monzug** [comment]
I do get an error message about corrupted data now, still no errors in the log.

![Screen Shot 2021-11-04 at 2 57 23 PM](https://user-images.githubusercontent.com/41396793/140326840-252d059c-0bb6-42ca-81cd-5859647c5be0.png)

again, I believe that when there is an error in the indexedDB file, it cannot be loaded.

**Comment by irina060981** [comment]
I will add some instructions - how to save and send me this corrupted alignment

**Comment by irina060981** [comment]
@monzug , I added the following action:
   when a user tries to open corrupted alignment data from IndexedDb and gets the erorr, an automatic download of the full IndexedDB data will be done
   
   Please try to open such alignment, get downloaded file and send me via email, or attach here (may be you will need to archive it)

**Comment by monzug** [comment]
Pls find attached two corrupted files (hope it's not the same file...).
[05-11_13-42-corrupted-alignment.json.zip](https://github.com/alpheios-project/alignment-editor-new/files/7486259/05-11_13-42-corrupted-alignment.json.zip)

[05-11_13-42-corrupted-alignment(1).json.zip](https://github.com/alpheios-project/alignment-editor-new/files/7486261/05-11_13-42-corrupted-alignment.1.json.zip)

**Comment by irina060981** [comment]
Monica, I need another file - I updated the code - please - try again to open a corrupted alignment and attach here downloaded files.

**Comment by monzug** [comment]
here are the two corrupted files
[08-11_14-51-corrupted-alignment-dbData(1).json.zip](https://github.com/alpheios-project/alignment-editor-new/files/7497450/08-11_14-51-corrupted-alignment-dbData.1.json.zip)
[08-11_14-51-corrupted-alignment-dbData.json.zip](https://github.com/alpheios-project/alignment-editor-new/files/7497451/08-11_14-51-corrupted-alignment-dbData.json.zip)

**Comment by irina060981** [comment]
Monica, I fixed the bug - and now you should be able to upload your alignments without problems.

**Comment by monzug** [comment]
yes. they both worked!!!! Thanks
