### ISSUE TITLE
Undo highlights only a portion of a split token

### ISSUE THREAD

**Issue by monzug** [alpheios-project/alignment-editor-new#609]
while retesting #548 I noticed an awkward scenario with undo.
1) highlight a token (it turned green) but then click on it again to deselect because I do not want to do an alignment.
2) go to edit text and split the token in two parts.
3) go back to align text and click on undo. only the first portion of token in question is highlighted.

Super minor bug. I mentioned here but I do not think it's worth fixing it.

**Comment by irina060981** [comment]
>found the reproducible scenario: in align text if I highlight the token and then deselect it (it does happen frequently thinking that I am in annotation mode), then in edit text the undo/redo are not active as if the token is in an alignment group.

The reason is the following:

When you select a token at the first time - it is added to a group.
At the moment when token is grouped - appliction clears history.
And we don't have a feature to restore history if a user changes his mins and deselect the token.

So there is no bug here - it is a result of clearing history workflow

_Originally posted by @irina060981 in https://github.com/alpheios-project/alignment-editor-new/issues/548#issuecomment-966688799_

**Comment by irina060981** [comment]
So it is not a bug

If you want to change it - we need to invent a new workflow for clearing history
