### ISSUE TITLE
Add modes to Options on Text Enter screen

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/alignment-editor-new#611]
after online discussion with @abrasax

1. create predefined Options preset:
   - Standard (it is default)
   - Advanced (specificslly for Pietro)
   - Custom - options could be defined manually

2. Add ability to see (but not update options for Standard and Advanced preset)

3. At first glance a user has a Standard preset. 

4. We don't expect to give users ability to create there own preset

@monzug , I created this issue to remember this task - but I believe we would need to have some final discussions before starting to work on it

**Comment by irina060981** [comment]
Presets should be stored in Local Storage similiar to options.

**Comment by irina060981** [comment]
Changed workflow for main options (on Text Enter Screen)

![image](https://user-images.githubusercontent.com/12377640/146513125-26fb6aae-2cc8-475d-8e10-9fb519628100.png)

- **Standard** and **Advanced** presets are predefined and couldn't be edited by the user
- **Custom** preset - is equal to Standard by default (but it could be changed - because it has its own default that is simply equal to Standard) and could be edited by the user

- if a user clicks on the preset's name - preset is selected and applications options are updated from its values
- if a user clicks on the eye icon - preset is shown but not selected
- selection is defined by background color

- options and the chosen preset are saved to LocalStorage and uploaded on application load
- changes to Custom preset are saved to LocalStorage and uploaded on application load (even if it is not selected)

- resetAll button do the following:
  - resets changes in Custom preset and uploaded its default
  - resets chosen preset to Standard (because it is defined as default)
  - uploads options from Standard preset

**Comment by monzug** [comment]
What I usually do in my testing is to try a new feature without reading the instructions (well, I admit that I do not like to read instructions to begin with...). anyhow, in this way I pretend to be a user trying a new functionality.
First thing I noticed is that the modes selection is NOT user friendly. if I click on the eye I see the Options, if I click on the mode I select the mode. Both share the same square that is itself selectable, so initially I always ended up in Standard mode.
1) I would suggest to separate the Options view from the mode selection, in order to avoid potential confusion.
2) Reset all button is available in Standard Options and in Advanced Options too, where it's totally useless as I am not able to edit/change anything. I would grey out the button from these two options view.
3) I think it  would be nice to know the mode I am on from the Align and Edit screen (when available), rather then going back to Enter text, then to Options to see the selected mode.

**Comment by irina060981** [comment]
>1. I would suggest to separate the Options view from the mode selection, in order to avoid potential confusion.

How exactly do you suggest to separate it from UI perspective?
I could suggest to reduce colored box and leave only title there.
And draw eye without background.
the behaviour won't change but it would be separated visually.
@monzug , may be you have some other suggestions?

>2. Reset all button is available in Standard Options and in Advanced Options too, where it's totally useless as I am not able to edit/change anything. I would grey out the button from these two options view.

Oh, I forgot that it is rendered on options , I could disable it as suggested or even hide.

>3. I think it would be nice to know the mode I am on from the Align and Edit screen (when available), rather then going back to Enter text, then to Options to see the selected mode.

Do you suggest to tupe it after screen Title?

**Comment by monzug** [comment]
I was thinking to sepate the eye from the mode, so if you make the box smaller with only the mode, and the eye outside the box, it should work.

I think it would be nice to say it sonewhere and it would be ideal next to screen tutke, as u suggested. However my undersranding is that Harry gas other plans in mind so hold on for now. You’ll have a call later so it might be a good moment for Harry to present his ideas.

**Comment by monzug** [comment]
Sorry but I am in the train as it’s difficult yo type… the Swiss mountains….

**Comment by abrasax** [comment]
Irina- let me know when you want a break from the vulnerability problem. I
wouldn't spend any more time on the UI until we have spoken again.

**Comment by irina060981** [comment]
It is outdated
